### ISSUE TITLE
setup.py fails in environments where locale != *utf8

### ISSUE THREAD

**Issue by sdelafond** [python-hyper/hpack#127]
With python3.5, in a "regular" C locale, opening HISTORY.rst fails because that file is utf8-encoded (python2.7 doesn't complain about that).

**Comment by Lukasa** [comment]
Yup, that seems like a likely problem. Mind supplying a PR to resolve the issue?

**Comment by sdelafond** [comment]
I was gonna add encoding=utf-8 to the open call, but that won't work in 2.7 unfortunately...

**Comment by Lukasa** [comment]
@sdelafond You want `codecs.open`.
