### ISSUE TITLE
Optionally do not decode to UTF-8

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hpack#13]
By default, `.decode()` returns UTF-8. Some systems, however, expect headers to be bytes and to worry about it themselves. We may optionally want to disable this automatic decoding of the text encoding, and instead to return byte strings.

**Comment by jimcarreer** [comment]
I'm off work today so I'll work on this, sounds super easy.

**Comment by Lukasa** [comment]
This is now resolved. =)
