### ISSUE TITLE
Broken hyperlinks

### ISSUE THREAD

**Issue by bricewge** [python-hyper/hpack#233]
The readme and Github's description link to http://python-hyper.org/hpack/ which returns 403.  Pypi's homepage link to http://hyper.rtfd.org/ which redirect to Hyper's docs: https://hyper.readthedocs.io/en/latest/.

https://hpack.readthedocs.io/en/latest/ is probably to be used instead.

**Comment by Kriechi** [comment]
This should be fixed now.
