### ISSUE TITLE
When will be the time to drop Python 2 compatibility?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [python-hyper/hpack#274]
I recently attempted to use [one of my favorite static analysis tools](https://www.youtube.com/watch?v=abvW0mOrDiY) with `hpack` and it choked on
```
try:  # pragma: no cover
    basestring = basestring
except NameError:  # pragma: no cover
    basestring = (str, bytes)
```
in `hpack.py` because it doesn't support analyzing Python 2 source. My impression at this time is that this isn't a problem with the tool; that more than four years after [the Python 2 turndown](https://pythonclock.org) it's appropriate for tools to drop support for analyzing Python 2 source.

------------
So... while I see that https://hyper.readthedocs.io/en/latest advertises that the `hyper` family of projects supports `2.7.9`-and-later in the Python 2 line, do y'all `hyper` maintainers have a notion of when you're going to be dropping Python 2 compatibility from the source?

**Comment by Kriechi** [comment]
Sounds good to me! Happy to review a PR, though not sure when we will ship the next major release to include the change.

**Comment by nathanielmanistaatgoogle** [comment]
Apologies that I didn't get to this on my own, and thanks much for the change! 🙂
